### ISSUE TITLE
revert "ensure_packages" changes

### ISSUE THREAD

**Issue by Ma27** [willdurand/puppet-nodejs#116]
as I was unable to reproduce the issue described in #78 I think the previous changes of ensure_packages should be reverted in order to clean up the code.

**Comment by Ma27** [comment]
moving to 2.0 as this may require a min requirement bump of puppetlabs-stdlib.

**Comment by willdurand** [comment]
:+1:

**Comment by Ma27** [comment]
see also the changes made in ticket #34 
I'll have a look at the changelog of puppetlabs-stdlib in order to check out what could go wrong.
If we have to bump the min version of puppetlabs-stdlib this will be fixed in 2.0 and not for 1.x

**Comment by Ma27** [comment]
many parts of the installer will be changed and then this can be fixed when rewriting some components
