### ISSUE TITLE
[RFC] use nvm

### ISSUE THREAD

**Issue by Ma27** [willdurand/puppet-nodejs#119]
nvm is a tool to enhance the management of cross-version support. Instead of the current, quite hacky approach, nvm would be a great alternative

**Comment by Ma27** [comment]
with nvm we could do something like this:

``` puppet
::nodejs::nvm { 'node-v5.4':
    ensure => present,
    version => 'v5.4.1',
    default => true,  # need a default instance for nvm
    # more params
}
```

For the removal we can do something like this:

``` puppet
::nodejs::nvm { 'node-v0.12':
    ensure => absent,
    version => 'v0.12',
}
```

The manifest itself can create a default version and then it is possible to switch between versions in the VM like this:

``` shell
nvm use 0.12
```

This could avoid hacks like creating weird symlinks for any version, but using a proper version manager to avoid more bugs.
This will come in 2.x as it will break much stuff and some big change should not come in a minor release. Furthermore the 1.x will still be supported, so people depending on the legacy approach can still rely on this.

**Comment by willdurand** [comment]
I'm all in favor of this :+1:

What we could do is:

- releasing a last (minor) `1.x` version, and providing support for it _via_ patch versions;
- going to 2.x for anything new.

**Comment by Ma27** [comment]
thanks for your feedback @willdurand 
As you can see we have currently two milestones for 1.9 and 2.0.

The 1.9 is the last minor release of the 1.x series and will have its own version branch.
I think we should provide at least two years support for this as the changes are quite heavy.

I'll finish the 1.9 release and then we can go for a second version of this module which will be developed in master. I think we should still support ruby 1.x and puppet 2.7 and 3.x as many users still rely on it (our mayflower-vagrant box still uses puppet3: https://atlas.hashicorp.com/mayflower/boxes/trusty64-puppet3)

For puppet-nodejs 3.x we can talk about puppet4 (because of the types), but definitely not now.

Another thing we should talk about is that we may submit the second version of our module for approval: https://forge.puppetlabs.com/approved

**Comment by Ma27** [comment]
labeling this as approved
