### ISSUE TITLE
rename refactorings

### ISSUE THREAD

**Issue by Ma27** [willdurand/puppet-nodejs#128]
there are some parameters that are poorly named.
Example:

``` puppet
::nodejs::npm { 'webpack': exec_as_user => 'vagrant', }
```

``exec_as_user`` looks like a boolean flag, but is used as string.
It should be analyzed where such changes exist in order to improve naming in 2.0

**Comment by willdurand** [comment]
:+1:

**Comment by Ma27** [comment]
in #122 I've started renaming some parameters for passing the package and directory as the approach of ``::nodejs::npm { '/dir:pkg': }`` is IMHO not that nice.
The code throws warnings if this behavior is still in use. The deprecation warnings should be removed, too.

**Comment by Ma27** [comment]
closing this for now. I'll open another issue with a detailed description what needs to be refactored at ``::nodejs::npm``
