### ISSUE TITLE
Evaluation Error: Unknown variable: '::http_proxy'

### ISSUE THREAD

**Issue by joshuaspence** [willdurand/puppet-nodejs#130]
Using this module fails when running with `strict_variables` enabled.

`Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Unknown variable: '::http_proxy'. at /home/josh/dotfiles/puppet/ext_modules/wget/manifests/fetch.pp:35:21  at /home/josh/dotfiles/puppet/ext_modules/nodejs/manifests/install.pp:116 on node deagle.engineering.syd2.internal`

**Comment by Ma27** [comment]
hey @joshuaspence, thanks for your report - I really appreciate that.

But in order to checkout what went wrong I require some more information: which OS do you use, which puppet version, which puppet-nodejs version, which puppet-wget version. And the related parts of your puppet manifest can be quite helpful.
Furthermore I think that's an issue related to maestrodev-wget: maestrodev/puppet-wget#62

**Comment by Ma27** [comment]
adding puppet4 label as I assume it is related to the strict mode of this version

**Comment by Ma27** [comment]
@willdurand If the guys from puppet-wget don't fix this soon, I have to think about another solution for downloading the nodejs source/executable (this could also relate to 2.x as nvm can be installed either with wget or curl)

**Comment by joshuaspence** [comment]
OS version is Ubuntu 15.10. Puppet version is 4.3.2. `puppet-nodejs` version is 1.90 and `puppet-wget` version is 1.7.1.

**Comment by joshuaspence** [comment]
Yes, I'm fairly certain that this is caused by https://github.com/maestrodev/puppet-wget/issues/62

**Comment by Ma27** [comment]
ok thank you.
Next week I'm gone, so I will add a notice about this issue in the readme and try to find a solution when I'm here again (which will be 1.9.2 then :))

Sorry for this issue, if they don't fix it, I think about doing the wget stuff manually.

**Comment by Ma27** [comment]
successfully reproduced the issue with a ``puppetlabs/ubuntu-14.04-64-puppet`` for vagrant and using the ``--strict_variables`` option for ``puppet apply``.
I'll evaluate whether there's a way to fix this issue with ``maestrodev/puppet-wget`` and unless I have to drop it.

**Comment by Ma27** [comment]
@joshuaspence is it possible for you to test the changes from the ``#130-strict-vars-support`` branch in order to verify that everything works fine?
