### ISSUE TITLE
Configurable nodejs download timeout

### ISSUE THREAD

**Issue by drscre** [willdurand/puppet-nodejs#139]
With slow internet connection, default timeout for nodejs::install::download::exec is sometimes not enough.
It would be great to have a 'timeout' option for nodejs::install::download class

**Comment by Ma27** [comment]
:+1: I'm in favor of this :)
I'll fix this when I have time to do that and then it will go intonthe 1.9 branch.

**Comment by Ma27** [comment]
see release 1.9.4
