### ISSUE TITLE
Add install_git flag

### ISSUE THREAD

**Issue by dragrom** [willdurand/puppet-nodejs#168]
### Description
 I already installed the git as package into my environment

### Steps to reproduce

include nodejs in my module give the error: Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Package[git] is already declared;

**Comment by Ma27** [comment]
may I ask how you're installing `git`?
We're using the `ensure_packages()` function, so when you install it the same way (with `ensure_packages`) there shouldn't be any conflict. (See here: https://github.com/willdurand/puppet-nodejs/blob/master/manifests/instance/pkgs.pp#L22-L24)

Furthermore I planned to evaluate whether or not `git` as dependency is really needed: I removed a lot of old code before releasing `2.0.0-alpha1` and it might be possible that the whole dependency is obsolete (will care about this before release `2.0.0-alpha2`)

**Comment by Ma27** [comment]
might be related to older issues such as #34 or #93 ...

**Comment by Ma27** [comment]
I think I've found the cause.
The `ensure_packages` function uses the `ensure_resource` function internally.
This creates new resources using `create_resources` if `defined_with_params` evaluates to false (https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/lib/puppet/parser/functions/ensure_resource.rb#L38-L44)

If you omit the `ensure => installed` argument (in the `pkgs.pp` it's added) it might cause conflicts.

/cc @willdurand I think you had to deal with this some years ago, this might be the cause...

**Comment by dragrom** [comment]
Maybe this will solve the problem:
class nodejs::instance::pkgs($install_ruby = false, $make_install = false, $install)git = true)
if $install_git {
  ensure_packages(['git'], { ensure =>  installed })
}

And remove git from ensure_packages(['tar', 'git', 'wget'], {
    ensure => installed,
  })

**Comment by Ma27** [comment]
possibly.

But I'd rather like to investigate whether we **really** need `git`. As I mentioned, it might have been obsolete since `2.0.0-alpha1`.

But to fix your problem: would you mind showing me how you install `git` in your puppet code? We might find a way to solve this before a `2.0.0-alpha2` release.

**Comment by Ma27** [comment]
@dragrom I just dropped the `git` usage entirely since it's not required for the actual installation (see my comment in #106 for more information)
