### ISSUE TITLE
NodeJS v7 support(ed)?

### ISSUE THREAD

**Issue by SebTM** [willdurand/puppet-nodejs#171]
### Description
I would need NodeJS v7 for a project - is it already supported or will it be in near future?

### Steps to reproduce
Setting version to "7" installs latest v6

### Further details
macOS 10.12.3, Vagrant 1.9.2, Virtualbox 5.1.19, Ubunut 16.04 LTS, Puppet 4.6.2
(Configuration done with PuPHPet)

Version v1.9.1 is used from PuPHPet

**Comment by Ma27** [comment]
could you please tell me which version of this module you're using? And how your puppet code actually looks like?

**Comment by SebTM** [comment]
Urg sry it's my fault! I thought PuPHPet is using your Puppet module because they are loading it in Puppetfile (https://github.com/puphpet/puphpet/blob/master/archive/puphpet/puppet/Puppetfile). Looking into their "puphpet"-module/manifests I found out that they don't. So it's not an issue of this package - I'm sorry!

**Comment by Ma27** [comment]
never mind :-)
