### ISSUE TITLE
npm packages not being installed globally

### ISSUE THREAD

**Issue by spengilley** [willdurand/puppet-nodejs#174]
### Description

When I run a puppet module which installs nodes and then uses the new package nom provider to install grunt, bower and protractor, I am unable to use any of thee programs by typing their name on the command line

### Steps to reproduce

    # Install node
    class { 'nodejs':
        version      => 'latest',
        make_install => false,
        require      => Class['base']
    }

    # Install node packages
    package {['grunt', 'bower', 'protractor']:
        ensure          => present,
        provider        => 'npm',
        install_options => ['-g'],
        require         => Class['nodejs']
    }

Type 

> grunt

Receive 

> -bash: grunt: command not found

### Expected behavior

I expect grunt, bower and protractor to be recognised on the command line

### Further details

On Debian/contrib-jessie64. Using Puppet version 3.78
I can see during the puppet run the following in the output
> /Stage[main]/Dev/Package[bower]/ensure: created

I can also see that grunt is installed in the following places

> /usr/local/node/node-v8.1.3/lib/node_modules/grunt
/usr/local/node/node-v8.1.3/lib/node_modules/grunt/lib/grunt
/usr/local/node/node-v8.1.3/lib/node_modules/grunt/node_modules/.bin/grunt
/usr/local/node/node-v8.1.3/lib/node_modules/grunt/node_modules/grunt-cli/bin/grunt
/usr/local/node/node-v8.1.3/lib/node_modules/grunt/bin/grunt
/usr/local/node/node-v8.1.3/bin/grunt

**Comment by Ma27** [comment]
thanks for your bug report. Could you please tell me which version of **this** module you're using?

**Comment by spengilley** [comment]
Hi there,

Of course. Version 2.0.0

**Comment by Ma27** [comment]
@spengilley you're right, I managed to reproduce this behavior and hope that I'll find some time next week :-)

**Comment by Ma27** [comment]
I just managed to research a little bit: it seems as no `prefix` is set which caused NPM to avoid setting create symlinks into the appropriate directory in `$PATH`.
In `1.9` we used an ugly script to add more `/usr/local/node` things into `$PATH`, so the prefix was unnecessary, but not this seems to cause issues.

I'll try to reserve some time to fix this next week, however a temporary workaround for you would be to create an `exec` resource in your manifest which runs the following command (assuming that `/usr/local/bin` is your install dir:

``` bash
npm set prefix /usr/local -g
```

**Comment by spengilley** [comment]
Thanks for the information and the work around!

**Comment by Ma27** [comment]
@spengilley I created a bugfix in #175. Would be cool if you could test the changes locally in order to confirm that the patch works? :-)

**Comment by spengilley** [comment]
Hi @Ma27 I can confirm that this worked wonderfully. I appreciate such a quick turn around.

Stephen

**Comment by Ma27** [comment]
patch landed in https://github.com/willdurand/puppet-nodejs/releases/tag/2.0.0-alpha3

thanks for reporting and for the feedback!
