### ISSUE TITLE
Does not work on Windows Server 2016

### ISSUE THREAD

**Issue by mountaindude** [willdurand/puppet-nodejs#176]
I realise this might be by design... but still.
I get the following error when doing a simple 

class { 'nodejs':
  version => 'v6.0.0',
}

Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README. at ["C:/ProgramData/PuppetLabs/code/environments/production/modules/nodejs/manifests/init.pp", 43]:
   (at C:/ProgramData/PuppetLabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at ["C:/ProgramData/PuppetLabs/code/environments/production/modules/nodejs/manifests/init.pp", 44]:
   (at C:/ProgramData/PuppetLabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Error: Could not autoload puppet/parser/functions/is_npm_provided: cannot load such file -- semver
Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/is_npm_provided: cannot load such file -- semver at C:/ProgramData/PuppetLabs/code/environments/production/modules/nodejs/manifests/install.pp:213:24  at C:/ProgramData/PuppetLabs/code/environments/production/modules/nodejs/manifests/init.pp:46 on node <server-id>

**Comment by Ma27** [comment]
I kept the `validate_*` functions to retain Puppet 3.x support for now.

As the release of `2.x` is (due to personal limitations) delayed, we might want to drop Puppet 3.x before a release.

**Comment by Ma27** [comment]
>  Error: Could not autoload puppet/parser/functions/is_npm_provided: cannot load such file -- semver
Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/is_npm_provided: cannot load such file -- semver at C:/ProgramData/PuppetLabs/code/environments/production/modules/nodejs/manifests/install.pp:213:24 at C:/ProgramData/PuppetLabs/code/environments/production/modules/nodejs/manifests/init.pp:46 on node 

To provide sufficient help however, it would be cool if you could give me some more information such as the module version in use to know what we're exactly talking about.

**Comment by Ma27** [comment]
closing for now due to lacking feedback of @mountaindude for several months now. If you are still interested in fixing this, just ping me and answer my questions %)
