### ISSUE TITLE
Nodejs missing in PATH after 2.0 version

### ISSUE THREAD

**Issue by mtomov** [willdurand/puppet-nodejs#177]
### Description

Before 2.0, the `/etc/profile.d/nodejs.sh` file used to look like this:

```
NODEJS_HOME=/usr/local/node/node-default

if [ -d "$NODEJS_HOME/bin" ] ; then
  export PATH="$NODEJS_HOME/bin:$PATH"
fi
```

Now, it looks like this:

```
export NODE_PATH=/usr/local/node/node-default/lib/node_modules
```

with no replacement of the lost functionality - modifying the PATH to include the location of the node executable.

Change was made in: https://github.com/willdurand/puppet-nodejs/commit/bcfdda3341aa8b0d885b40e9a6ab7f90859f9f3e

### Expected behavior

The problem occurs in my particular case for a `cron` job, ran with with the `-l` flag for a login shell. Before, the cron path  - `PATH=/usr/bin:/bin` (very bare as you might notice) would be appended with the path to the node binary, while after, `node` is not found.

### Further details

- Ubuntu

Thank you!

**Comment by Ma27** [comment]
all executables will be deployed into `/usr/local/bin` (see https://github.com/willdurand/puppet-nodejs/blob/master/manifests/params.pp#L17) by default.

``` puppet
class { '::nodejs':
  target_dir => '/your/desired/target/path',
}
```

**Comment by mtomov** [comment]
I see. There's definitely a few solutions to the problem in my case ( I can for example add custom script in `profiles.d` folder to append `/usr/local/bin` to the `PATH`). 

Maybe if you have time would be nice to add a line to the changelog saying that this `PATH` modification was removed. Even without this, I think you can close the issue.

Thanks for the response, and thank you for supporting this library!
