### ISSUE TITLE
Install NodeJS from a different source

### ISSUE THREAD

**Issue by vrmerlin** [willdurand/puppet-nodejs#185]
We'd like to be able to build a system without going out to the internet. Does your package support local repos, if we download the Node.js packages manually?

**Comment by Ma27** [comment]
thanks a lot for filing an issue!

referring to Node.js package**s** is a bit ambiguous to me. do you mean simple npm packages or the package with `node` and `npm` itself?
Until now it's not supported, but at least the offline installation of `node` shouldn't be too hard to implement.

**Comment by vrmerlin** [comment]
Sorry, didn't mean to be confusing. I meant the installation of Node.js and NPM itself, not the other npm packages.

John

On Oct 25, 2018 4:43 PM, Maximilian Bosch <notifications@github.com> wrote:

thanks a lot for filing an issue!

referring to Node.js packages is a bit ambiguous to me. do you mean simple npm packages or the package with node and npm itself?
Until now it's not supported, but at least the offline installation of node shouldn't be too hard to implement.

**Comment by Ma27** [comment]
thanks a lot for the elaboration. Let's see if I have sufficient timeone the weekend to implement this :)

**Comment by Ma27** [comment]
So, I just had some thoughts about how to achieve what you want, you can specify "local files" in the `files/` directory of a Puppet module.

Then it should be sufficient to copy from `module://url` the relevant binaries into the target directory.

Such a solution may look like this in the end:

``` puppet
class { '::nodejs':
  src => 'puppet://modules/your-custom-module/nodejs-10',
}
```

Unfortunately I didn't have sufficient time on the weekend, I hope that I can do this next weekend.
But if you want to implement this yourself, a PR is always welcome :-)

**Comment by vrmerlin** [comment]
Sorry for the delay - I've been called up for jury duty.....

I think that's what I'm looking for.  I'll be using a URL. So, if I manually download the Node.js application from here:

https://nodejs.org/dist/v10.13.0/node-v10.13.0-linux-x64.tar.xz

and put it on my local apache server as:

http://myserver/repo/nodejs/node-v10.13.0-linux-x64.tar.xz

Then my code would be:

```
class { '::nodejs':
   src => 'http://myserver/repo/nodejs',
   version => '10.13.0'
}
```

That sound right?

**Comment by Ma27** [comment]
yeah, that's the overall idea.
But one question: do you intend to place your nodejs archive on a remove location (like in your example) or locally inside a module? Because I'm quite certain that supporting both might be a bit of a challenge (but it's not absolutely impossible I guess)

**Comment by Ma27** [comment]
you may want to have a look at #189 btw :)
I'll see when I have sufficient time to build a release, but this should include your request as well, right?

**Comment by vrmerlin** [comment]
Thank you for adding this capability!! I really appreciate your responsiveness.

**Comment by vrmerlin** [comment]
I'd like to test this new capability -- is 2.1 coming out soon?

**Comment by Ma27** [comment]
would you mind checking out this branch and e.g. deploy this into a VM?

I planned to do the release in december (not sure when I have sufficient time to recheck everything and releasing it)

**Comment by vrmerlin** [comment]
Ok, I gave it a try, but am a bit puzzled by the results.  First, I'm not sure if I use the Linux binaries or the  source download. I tried both. When I tried the source, like this:

```
 class { 'nodejs':
   source => 'http://myrepo.foo.bar:6000/local_repo/node/node-v10.14.1.tar.gz',
 }
```

I got this error:

```
Notice: /Stage[main]/Nodejs::Instances/Nodejs::Instance[nodejs-custom-instance-v10.14.1]/Exec[nodejs-unpack-v10.14.1]/returns:
Notice: /Stage[main]/Nodejs::Instances/Nodejs::Instance[nodejs-custom-instance-v10.14.1]/Exec[nodejs-unpack-v10.14.1]/returns: gzip: stdin: unexpected end of file
Notice: /Stage[main]/Nodejs::Instances/Nodejs::Instance[nodejs-custom-instance-v10.14.1]/Exec[nodejs-unpack-v10.14.1]/returns: tar: Child returned status 1
Notice: /Stage[main]/Nodejs::Instances/Nodejs::Instance[nodejs-custom-instance-v10.14.1]/Exec[nodejs-unpack-v10.14.1]/returns: tar: Error is not recoverable: exiting now
Error: 'tar -xzvf node-v10.14.1-linux-x64.tar.gz -C /usr/local/node/node-v10.14.1 --strip-components=1' returned 2 instead of one of [0]
Error: /Stage[main]/Nodejs::Instances/Nodejs::Instance[nodejs-custom-instance-v10.14.1]/Exec[nodejs-unpack-v10.14.1]/returns: change from 'notrun' to ['0'] failed: 'tar -xzvf node-v10.14.1-linux-x64.tar.gz -C /usr/local/node/node-v10.14.1 --strip-components=1' returned 2 instead of one of [0]
Notice: /Stage[main]/Nodejs::Instances/File[/usr/local/node/node-default]: Dependency Exec[nodejs-unpack-v10.14.1] has failures: true
```

So, it seems to be downloading the file, but can't open it. When I do a ```tar -xzvf``` on the command line it works fine. Any ideas?

**Comment by Ma27** [comment]
This tarball contains NodeJS sources, right? in that case you'd have to specify `make_install => true`. If not, this is definitely an issue in the code.

Either way, I see that the documentation in this regards needs improvement :)

**Comment by vrmerlin** [comment]
But isn't if failing trying to uncompress/untar, before it even gets to thinking about if it's source or binaries?

**Comment by Ma27** [comment]
yeah, in case of `make_install => false` it expects a different file name (which is wrongly documented)

**Comment by vrmerlin** [comment]
Ah, ok. I actually just want to install the binaries, so I'll try that again tomorrow at work, and see if I can make that work.

**Comment by vrmerlin** [comment]
I went back to the binaries, trying this:

```
class { 'nodejs':
  source => 'http://myrepo.foo.bar:6000/local_repo/node/node-v10.14.1-linux-x64.tar.xz',
}
```

It fails, with this error:

```
Notice: /Stage[main]/Nodejs::Instances/Nodejs::Instance[nodejs-custom-instance-v10.14.1]/Exec[nodejs-unpack-v10.14.1]/returns:
Notice: /Stage[main]/Nodejs::Instances/Nodejs::Instance[nodejs-custom-instance-v10.14.1]/Exec[nodejs-unpack-v10.14.1]/returns: gzip: stdin: unexpected end of file
Notice: /Stage[main]/Nodejs::Instances/Nodejs::Instance[nodejs-custom-instance-v10.14.1]/Exec[nodejs-unpack-v10.14.1]/returns: tar: Child returned status 1
Notice: /Stage[main]/Nodejs::Instances/Nodejs::Instance[nodejs-custom-instance-v10.14.1]/Exec[nodejs-unpack-v10.14.1]/returns: tar: Error is not recoverable: exiting now
Error: 'tar -xzvf node-v10.14.1-linux-x64.tar.gz -C /usr/local/node/node-v10.14.1 --strip-components=1' returned 2 instead of one of [0]
Error: /Stage[main]/Nodejs::Instances/Nodejs::Instance[nodejs-custom-instance-v10.14.1]/Exec[nodejs-unpack-v10.14.1]/returns: change from 'notrun' to ['0'] failed: 'tar -xzvf node-v10.14.1-linux-x64.tar.gz -C /usr/local/node/node-v10.14.1 --strip-components=1' returned 2 instead of one of [0]
```

Why is the ".xz" becoming a ".gz"? Also, with a .xz, it should be ```tar -xvf```, not ```tar -xzvf``` (at least what's what I see from the command line.

I tried it with and without ```make_install => false``` and it didn't make a difference.

**Comment by vrmerlin** [comment]
Any ideas on why I can't get this to work? Seems like we are close...

**Comment by Ma27** [comment]
yeah sorry, I forgot about that. I'll have a deeper look at this tomorrow ;)

**Comment by Ma27** [comment]
As you've surely noticed, it's been a fairly bad idea to force users to provide filenames that have the same convention as the files distributed by `nodejs.org/dist`. I updated the code to allow users to specify `$source` with any name (as long as it's some kind of tarball with either nodejs binaries or nodejs sources).

Please keep for `.tar.xz` in mind that you'd have to install `xz-utils` (which is now documented in the readme) on certain platforms by yourself (we don't use `.tar.xz` by default), then it should work for you as well.
In case some usage examples help I recommend [the acceptance tests](https://github.com/willdurand/puppet-nodejs/blob/master/spec/acceptance/nodejs_spec.rb). For further issues/questions feel free to ping me :)

I'll release somewhere before or after the holidays, I'm not sure yet as it depends on how much free time I have then and how much (negative) feedback I get for the current state of master.

**Comment by Ma27** [comment]
@vrmerlin does the current state work for you? If so, I'd prepare a release tonight :)

**Comment by vrmerlin** [comment]
sorry, i missed your notification -- yes it seems to work for me.
