### ISSUE TITLE
An error occurs when uninstalling an npm package using ensure => 'absent'

### ISSUE THREAD

**Issue by bluser86** [willdurand/puppet-nodejs#190]
### Description

When trying to use the npm provider to ensure an npm package is removed an error occurs:

`Error: Could not set 'absent' on ensure: undefined local variable or method 'resources' for Package[package-name](provider=npm):Puppet::Type::Package::ProviderNpm at /tmp/vagrant-puppet/modules-85eb9efd0de6ebfdc3619e4fd60be6c4/profile/manifests/node.pp:4`

### Steps to reproduce

First install a package using:

```
include ::nodejs
package { 'uglify-js' :
  provider => 'npm',
  ensure   => 'present',
  require => Class['nodejs'],
}
```

Then remove the package again by altering the ensure to 'absent':

```
include ::nodejs
package { 'uglify-js' :
  provider => 'npm',
  ensure   => 'absent',
  require => Class['nodejs'],
}
```

### Expected behavior

The npm provider successfully uninstalls the package.

### Further details

- OS: Ubuntu 16.04 in a virtualized environment using vagrant and virtualbox.
- Vagrant: 2.2.5
- Puppet: 4.10.12
- Facter: 3.6.10

I have resolved this myself by editing `lib/puppet/provider/package/npm.rb` with the following diff:

```
diff --git a/lib/puppet/provider/package/npm.rb b/lib/puppet/provider/package/npm.rb
index 70386df..2bf0562 100644
--- a/lib/puppet/provider/package/npm.rb
+++ b/lib/puppet/provider/package/npm.rb
@@ -80,7 +80,7 @@ Puppet::Type.type(:package).provide :npm, :parent => Puppet::Provider::Package d
 
   def uninstall
     options = ['--global']
-    options += join_options(resource[:uninstall_options]) if resources[:uninstall_options]
+    options += join_options(resource[:uninstall_options]) if resource[:uninstall_options]
     npm('uninstall', *options, resource[:name])
   end
 end
```

Changing the name of the `resources` variable to `resource` fixes the issue and the packages are removed correctly.

**Comment by Ma27** [comment]
Thanks a lot for your report! This actually seems like a regression. Would you mind, filing a PR? Otherwise I'd fix this during the next days :)

**Comment by bluser86** [comment]
Will do!
