### ISSUE TITLE
Uninstall nodejs using puppet

### ISSUE THREAD

**Issue by jaykumbhani** [willdurand/puppet-nodejs#40]
@willdurand 
How do i uninstall this package using puppet?

Thanks

**Comment by Ma27** [comment]
@jaykumbhani sry, I don't really understand this feature request. Could you please add some pseudo code how it should look like and then we can talk about it.
If you don't need that feature anymore (the ticket is pretty old) then we may close this

**Comment by Ma27** [comment]
ok, I'd propose the following code snipped:

``` puppet
::nodejs::uninstall { 'node-v0.12.2':
}
```

**Comment by grafjo** [comment]
@Ma27 why not ensure => absent?

**Comment by jaykumbhani** [comment]
I don't use puppet anymore...

Chef is better tool to go with.

Thanks
Jay

On Wed, Jan 20, 2016 at 4:16 AM, grafjo <notifications@github.com> wrote:

> @Ma27 <https://github.com/Ma27> why not ensure => absent?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/willdurand/puppet-nodejs/issues/40#issuecomment-173012909>
> .
>



-- 
*Jay Kumbhani*
Director - Software Engineering | *Zymr, Inc. *| www.zymr.com
<http://www.zymrinc.com/> |
M: +91 9725410001

-- 
============================================================================
IMPORTANT NOTICE: The information in this e-mail and any attached files is 
CONFIDENTIAL and may be legally privileged or prohibited from disclosure 
and unauthorised use. The views of the author may not necessarily reflect 
those of Zymr, Inc. It is intended solely for the addressee, or the 
employee or agent responsible for delivering such materials to the 
addressee. If you have received this message in error please return it to 
the sender then delete the email and destroy any copies of it. If you are 
not the intended recipient, any form of reproduction, dissemination, 
copying, disclosure, modification, distribution and/or publication, or any 
action taken or omitted to be taken in reliance upon this message or its 
attachments is prohibited and may be unlawful. At present the integrity of 
e-mail across the Internet cannot be guaranteed and messages sent via this 
medium are potentially at risk. All liability is excluded to the extent 
permitted by law for any claims arising as a result of the use of this 
medium to transmit information by or to Zymr, Inc.

**Comment by Ma27** [comment]
thx @grafjo , edited the pseudo code

**Comment by Ma27** [comment]
@jaykumbhani how unfortunate, but as the usecase is legit, I'll implement this for 1.9 :)
