### ISSUE TITLE
Automatically require nodejs

### ISSUE THREAD

**Issue by mcandre** [willdurand/puppet-nodejs#62]
Would it be possible to have puppet-nodejs automatically, implicitly, require nodejs?

Other puppet modules do this. As a puppet user, I feel like puppet should be automating more, not requiring me to remember that X module requires Y package.

**Comment by Ma27** [comment]
@mcandre being honestly I don't really understand what you want. It would be nice to provide a bit pseudo-code so I can see what you mean..

**Comment by Ma27** [comment]
closing due to no response. Furthermore I didn't see any puppet providers requiring a puppet class.
