### ISSUE TITLE
Could not install NodeJS via puppet.

### ISSUE THREAD

**Issue by trinsitw** [willdurand/puppet-nodejs#81]
I could not install NodeJS via puppet.
Error message was "Could not retrieve fact='nodejs_stable_version'"
I would like your advice. Any help is deeply appreciated. Thank you.

Vagrant v1.6.5 for MS Windows
Oracle VM VirtualBox v4.3.20 for MS Windows
Vagrant runs behind a HTTP proxy. Windows environment as attached.

![github_question](https://cloud.githubusercontent.com/assets/10149549/5388542/59387bb2-811f-11e4-98b9-e683e81f1045.gif)
-------start Vagrantfile------------
\# -*- mode: ruby -*-
\# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "puppetlabs/ubuntu-12.04-64-puppet"
  config.vm.provision "shell", inline: "puppet module install puppetlabs-stdlib"  
  config.vm.provision "shell", inline: "puppet module install maestrodev-wget"  
  config.vm.provision "shell", inline: "puppet module install willdurand-nodejs"  

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "provision/manifests"
    puppet.manifest_file = "default.pp"
    puppet.module_path = "provision/modules"
  end
 end
-------end   Vagrantfile---------------

Puppet's provision\manifests\default.pp starts with the line "include nodejs"

Here's my vagrant up output.
------start vagrant up----------------
D:\vagrant\bancadev>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'puppetlabs/ubuntu-12.04-64-puppet'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'puppetlabs/ubuntu-12.04-64-puppet' is up to date...
==> default: Setting the name of the VM: bancadev_default_1418267345449_15050
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring proxy for Apt...
==> default: Configuring proxy environment variables...
==> default: Mounting shared folders...
    default: /vagrant => D:/vagrant/bancadev
    default: /tmp/vagrant-puppet-3/manifests => D:/vagrant/bancadev/provision/manifests
    default: /tmp/vagrant-puppet-3/modules-0 => D:/vagrant/bancadev/provision/modules
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1117:in `issue_deprecation_warning')
==> default: Notice: Preparing to install into /etc/puppet/modules ...
==> default: Notice: Downloading from https://forgeapi.puppetlabs.com ...
==> default: Notice: Installing -- do not interrupt ...
==> default: /etc/puppet/modules
==> default: ????????? puppetlabs-stdlib (v4.4.0)
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1117:in `issue_deprecation_warning')
==> default: Notice: Preparing to install into /etc/puppet/modules ...
==> default: Notice: Downloading from https://forgeapi.puppetlabs.com ...
==> default: Notice: Installing -- do not interrupt ...
==> default: /etc/puppet/modules
==> default: ????????? maestrodev-wget (v1.5.6)
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1117:in `issue_deprecation_warning')
==> default: Notice: Preparing to install into /etc/puppet/modules ...
==> default: Notice: Downloading from https://forgeapi.puppetlabs.com ...
==> default: Notice: Installing -- do not interrupt ...
==> default: /etc/puppet/modules
==> default: ????????? willdurand-nodejs (v1.8.4)
==> default:   ????????? maestrodev-wget (v1.5.6)
==> default:   ????????? puppetlabs-stdlib (v4.4.0)
==> default: Running provisioner: puppet...
==> default: Running Puppet with default.pp...
==> default: stdin: is not a tty
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1117:in `issue_deprecation_warning')
==> default: Could not retrieve fact='nodejs_stable_version', resolution='<anonymous>': Connection timed out - connect(2)
==> default: Could not retrieve fact='nodejs_latest_version', resolution='<anonymous>': Connection timed out - connect(2)
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
==> default: Error: Invalid version string ''! at /etc/puppet/modules/nodejs/manifests/install.pp:183 on node localhost.mathregit.group
==> default: Wrapped exception:
==> default: Invalid version string ''!
==> default: Error: Invalid version string ''! at /etc/puppet/modules/nodejs/manifests/install.pp:183 on node localhost.mathregit.group
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

D:\vagrant\bancadev>
------end   vagrant up----------------

![github_question](https://cloud.githubusercontent.com/assets/10149549/5388573/ea601596-811f-11e4-9af9-a28278f0a086.gif)

**Comment by eperdeme** [comment]
I think the issue is related to;
http://www.jethrocarr.com/2014/08/14/ruby-nethttp-proxies/

Not to hot at ruby but the current code ignores http_ENV arguments.

**Comment by grafjo** [comment]
@eperdeme thx for that hint!

**Comment by grafjo** [comment]
@trinsitw maybe you wanna try this one https://github.com/willdurand/puppet-nodejs/pull/84 - feedback is welcome!
