### ISSUE TITLE
Add support for npm version

### ISSUE THREAD

**Issue by DracoBlue** [willdurand/puppet-nodejs#85]
Hello,

currently only the shipped version of npm is available after package installation. If one updates npm with npm install -g npm and afterwards decides to use puppet to choose another version of nodejs: the updated npm will be overruled.

Is it possible (/or a pull request appriciated) to choose a specific npm version?

**Comment by grafjo** [comment]
hi @DracoBlue,
pull request are always appriciated :+1: 

The thing is - don't update npm by yourself or run `package {'npm': provider => 'npm', ensure => 'latest'}` ... because this module has no knowledge about the npm update. 

Maybe you have an clever idea how this module can be improved by updating npm to a newer version than the nodejs delivered one.

@willdurand what do you think about this? Is it good or bad to integrate an updated version of npm?
In my opinion it's an bad idea and out of scope of this module.

**Comment by willdurand** [comment]
> In my opinion it's an bad idea and out of scope of this module.

exactly my thoughts, so :-1:

**Comment by BenLiyanage** [comment]
Hey--I think I needed a newer version of npm recently.  This sounds like a good feature to me.  I have little node experience though, just building out the infrastructure for someone else on the team.  I will try a rebuild soon w/o the updated npm version and see if it was actually necessary for our deploy.

**Comment by DracoBlue** [comment]
I fixed it with the following part for my project:

``` puppet
package { "npm":
  provider => "npm",
  ensure => "latest" // or a specific version
}
```

and added a `notify => Package["npm"]` to the `nodejs` class definition.

**Comment by ErikEvenson** [comment]
@DracoBlue I wish that would work -- but it doesn't for me.  I have noticed that if you use the plugin to install npm, it will work fine on subsequent applies.

**Comment by DracoBlue** [comment]
@ErikEvenson we use `ensure => "2.4.1"` for a specific npm version => this should work, doesn't it?

**Comment by ErikEvenson** [comment]
@DracoBlue npm is successfully installed, but afterwards, the npm provider will not work for other global packages.

**Comment by Ma27** [comment]
I've just had a look at the code and it should be possible to implement this.
@willdurand are you still :-1: or should we implement this?

**Comment by Ma27** [comment]
the actual issue is that by default the npm version is shipped with the node package downloaded from nodejs.org, so exchanging it will be difficult. As npm is also a npm package, the only possible solution would be to use it (although it's quite hacky)
