### ISSUE TITLE
root group

### ISSUE THREAD

**Issue by Wuntenn** [willdurand/puppet-nodejs#87]
I just lost a few days thinking I've been doing something wrong It was staring me in the face when i went through the source code a few times.

Could you please add a note to say that the user must be in the 'root' group for this module to work correctly or allow the user to specify the groups that own they key files generated by this module.

This isn't a requirement of any of the other modules that I've used from Puppetlabs. I was stumped as to why these two modules didn't work... now I see that they are both similar in this aspect!!

**Comment by grafjo** [comment]
I guess this module was developed with the idea of running puppet as the root user.
