### ISSUE TITLE
EACCESS errors

### ISSUE THREAD

**Issue by gaboAcosta** [willdurand/puppet-nodejs#88]
Hi guys I was just trying to install some packages using nodejs from willdurand and I noticed that on my vagrant box I cannot manually add a package without using sudo, It is my understanding that nodejs is preferably used without sudo (although I know this is different on more recent versions).

So I was wondering if there could be a feature request for installing nodejs without sudo privileges.

**Comment by grafjo** [comment]
hi @gaboAcosta,
can you show us your manifest please?
One thing you have to keep in mind is that this module installs a packag globally.

**Comment by willdurand** [comment]
ping @gaboAcosta

**Comment by gaboAcosta** [comment]
Nevermind about this, the days of NodeJS have changed and now NodeJS is not so freaky with the sudo as it used to be.
