### ISSUE TITLE
excessively verbose scrollback

### ISSUE THREAD

**Issue by parhamr** [willdurand/puppet-nodejs#89]
Full disclosure: this is a minor complaint, I have no intention of fixing it myself, and I am not terribly familiar with conventions of the Node.js ecosystem.

The scrollback during installation is incredibly verbose: I count 11,928 lines of content when I `require nodejs` at module version `1.8.5`. I think the least useful scrollback is `Exec[nodejs-unpack-v0.12.0]`.

I’m thinking a flag to change the log level would be useful. At the very least, I would want the unpack lines redirected to `/dev/null`.

**Comment by parhamr** [comment]
Issue mitigated with:

```puppet
  Exec <| title == "nodejs-unpack-v0.12.0" |> {
    # silence the noisy Node.js routines
    loglevel => debug
  }
```

**Comment by willdurand** [comment]
:+1:
