### ISSUE TITLE
Disable cache

### ISSUE THREAD

**Issue by deniak** [willdurand/puppet-nodejs#90]
It would be good to be able to disable the cache for the `latest version` and `stable version` so it won't create an error if `nodejs.org` is unavailable.

**Comment by grafjo** [comment]
I thought that the cache feature is solving the nodejs.org offline issue?

**Comment by deniak** [comment]
I guess the question is more to query `nodejs.org` *only* if you need know the latest/stable versions. If you don't care about that and want to use a specific version of `node`, there's no need to query `nodejs.org`

**Comment by sedan07** [comment]
@deniak see PR: #92

**Comment by deniak** [comment]
@sedan07 great. I hope @willdurand will agree with this PR :)

**Comment by Ma27** [comment]
PR #92 will be fixed when working on 2.0

**Comment by Ma27** [comment]
#147 is in progress, when everything is done, this ticket can be closed.

**Comment by Ma27** [comment]
fixed in #147
