### ISSUE TITLE
Install globals with non-root

### ISSUE THREAD

**Issue by ErikEvenson** [willdurand/puppet-nodejs#96]
I would like to install npm global packages with my vagrant user after provisioning.  Currently, I add this to my puppet node:

```
  # Allow vagrant user to global install npm packages
  exec { 'chown node directory':
    command => '/bin/chown -R vagrant:vagrant /usr/local/node/',
    path    => '/bin',
    user    => 'root',
  }
```

Is there a better way to do this -- perhaps by telling the plugin to use a different npm ```prefix``` setting?

**Comment by grafjo** [comment]
This will not work ... at the moment root owns '/usr/local/node/'.

Why not using puppet to install npms? See https://github.com/willdurand/puppet-nodejs#npm-provider for more details.

**Comment by ErikEvenson** [comment]
This works fine actually.  I do use puppet to install global npm packages, but I'd also like to be able to add global npm packages at the command line as the vagrant user.

**Comment by ErikEvenson** [comment]
You can see a full example of how I do this with this dev box: https://github.com/ErikEvenson/devbox.  Specifically, see https://github.com/ErikEvenson/devbox/blob/master/puppet/local_modules/dev_base/manifests/init.pp#L69-L75.

It would be nice if there was a cleaner way to do this.
