### ISSUE TITLE
Set NODE_PATH in nodejs.sh

### ISSUE THREAD

**Issue by ErikEvenson** [willdurand/puppet-nodejs#97]
Shouldn't this module set the ```NODE_PATH``` environment variable in the ```nodejs.sh``` file added to ```profile.d```?

**Comment by willdurand** [comment]
it might be

**Comment by ErikEvenson** [comment]
I do this in my dev boxes with something like this: https://github.com/ErikEvenson/devbox/blob/85b312fe083bd7a5807e136a5df28a8c16a7ce96/puppet/local_modules/dev_base/manifests/init.pp#L18-L22

**Comment by willdurand** [comment]
sounds good to me

**Comment by Ma27** [comment]
@ErikEvenson feel free to open a PR

**Comment by Ma27** [comment]
:+1:
