### ISSUE TITLE
Use standard naming convention for gemfile

### ISSUE THREAD

**Issue by sedan07** [willdurand/puppet-nodejs#99]
Currently the gemfile is called `.gemfile` but the standard naming convention for a gemfile is simply `Gemfile`. This means before running any bundler commands you need to explicitly tell it the name of the gemfile, if standards were adhered to this would be unnecessary and reduce complexity of installing dependencies and running specs. I'm not aware of any advantages of using a non-standard name for the gemfile?

**Comment by willdurand** [comment]
Yes, I know. I did that to avoid polluting the project directory, but I admit it is not ideal.. It's not so bad though as it's not used except for testing purpose, so I'll probably keep it as is. I don't do that on other projects though ;)
